### PR TITLE
Update Footer Links

### LINKED ISSUE #120: `404` from some footer links
Lead to `404` not found:
- https://testnet.ironfish.network/careers
- https://testnet.ironfish.network/blog
- https://testnet.ironfish.network/docs/whitepaper/1_introduction

### PR DESCRIPTION
**Pull request by devopsralf**
Fixes #120

### CODE REVIEW

**Comment by dguenther** [comment]
Thanks for the contribution! Could you also update the "About" and "FAQ" links in that file to point to ironfish.network? The end-to-end tests need to be updated as well, then this should be good to go.

**Comment by brekk** [comment]
> The end-to-end tests need to be updated as well, then this should be good to go.
@devopsralf You can find the integration tests here: https://github.com/iron-fish/website-testnet/blob/master/cypress/integration/pages/about.ts#L11

**Comment by devopsralf** [comment]
Excellent. I'll get those updated.

**Comment by devopsralf** [comment]
@brekk Additional Links updated as well as the Cypress Test

**Review by dguenther — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
